### ISSUE TITLE
New service advisor view

### ISSUE THREAD

**Issue by scaspers** [scaspers/CA-Portal#4]
This is the info we would want on this report.

1. ~customerWaiting flag of some sort  (thinking if color is used then yellow for waiting)~
2. ~inspectionCompleted flag of some sort (red) . flag if there are RS's (no detail)~
4. ~~orderID~~
5. ~~clientID, clientName~~
6. ~~vehicleYear, vehicleMake, vehicleModel, vehicleLicense~~
7. ~~vehicleID~~
8. ~~vehicleOdometer~~
9. ~~vehicleEngine and vehicleTransmission~~
10. ~~vehicleOptions~~
11. ~vehicleNotes~
12. ~workDesc~
13. ~orderNotes~
14. ~Inspection Results (By Priority tab)~
15. ~CannedResponses.Response    (not the description)~
16. ~Note~
17. ~Measurements~
18. ~Images~
19. ~Include checklistitems that were not answered at the bottom (as Unanswered or Unchecked)~
20. ~Can we auto expand all items or all item with responses, measurements or notes? (priority tab only)~
21. ~Can the measurements just show with out us clicking the link?~
22. ~Can the order number be slightly larger and followed by the Tech#?~
23. ~In the vehicle Details section right justify the labels and left justify the data?~

**Comment by DanielCaspers** [comment]
@scaspers @YoMurphy this is what I have so far for you. 

All remaining items take more work that isn't done yet. 

Also, providing point 18 requires architectural change since the REST interface will have to provide some sort of mechanism for either turning on/off the filtering unanswered checklist items, or the client will have to get everything and I'll have to make CA-Portal facing customers filter. 

![image](https://user-images.githubusercontent.com/6056563/39101231-71137fe2-465c-11e8-960c-ff068b368ade.png)

![image](https://user-images.githubusercontent.com/6056563/39101243-9853c1e8-465c-11e8-86b6-2ea5e61433ac.png)

**Comment by DanielCaspers** [comment]
[CA-Portal_ServiceWriter_Build01_DI.zip](https://github.com/scaspers/CA-Portal/files/1936249/CA-Portal_ServiceWriter_Build01_DI.zip)
[CA-Portal_ServiceWriter_Build01_DI2.zip](https://github.com/scaspers/CA-Portal/files/1936252/CA-Portal_ServiceWriter_Build01_DI2.zip)

**Comment by DanielCaspers** [comment]
[CA-Portal_ServiceWriter_Build02_DI2.zip](https://github.com/scaspers/CA-Portal/files/1936350/CA-Portal_ServiceWriter_Build02_DI2.zip)

**Comment by DanielCaspers** [comment]
[CA-Portal_ServiceWriter_Build02_DI.zip](https://github.com/scaspers/CA-Portal/files/1938543/CA-Portal_ServiceWriter_Build02_DI.zip)

**Comment by scaspers** [comment]
Input on the SA view so far: ( I'll edit this as more comments come in )

1. Can we auto expand all level 1's & 2's?
2. Can the measurements just show with out us clicking the link?
3. Can the order number be slightly larger and followed by the Tech#?

**Comment by DanielCaspers** [comment]
All are doable. Still waiting for the dust to settle before jumping in to make sure we don't get competing requests.

1. Auto expanding 1's and 2's may take a few hours to do right, and I'll probably want to find a way to also make that a good enough solution where I'd consider bringing that functionality into both branches of code. **Do you need auto expansion for both grouped and individual items, or just one or the other?** 
2. Sure, I can do that but will patch into the branch instead of making it prepared for any future back-porting.
3. Yes. **Would you like this to also happen in the customer facing view? Would you like to let customer's see the technician who inspected their vehicle?**

**Comment by scaspers** [comment]
For the Customer waiting and inspection complete flags:
WAITING: 
<i class="material-icons.md-36" style="color:dodgerblue;" title="Customer Waiting">assignment_ind</i>
Insp Complete:
<i class="material-icons.md-36" style="color:red;" title="Action Required">notifications_active</i>

Use also in [DI #102](https://github.com/DanielCaspers/DigitalInspection/issues/102)

**Comment by DanielCaspers** [comment]
[CA-Portal_ServiceWriter_Build03_DI2.zip](https://github.com/scaspers/CA-Portal/files/1959373/CA-Portal_ServiceWriter_Build03_DI2.zip)

[CA-Portal_ServiceWriter_Build03_DI.zip](https://github.com/scaspers/CA-Portal/files/1959376/CA-Portal_ServiceWriter_Build03_DI.zip)

**Comment by DanielCaspers** [comment]
I placed the unanswered items at the top for now because I made the DI implementation default to 0 for Unknown in my enumeration. I can reorder them to the bottom if desired (especially for those who want to check in periodically during inspection before its complete), but it will take additional work to make sure no breaking changes will occur because of it.

Also, I'm letting service writers "dog-food" the idea of only allowing expansion icons when there is something inside worth looking at. It would be only a few minutes of change to bring that over to the priority tab on the customer facing version.

**Comment by DanielCaspers** [comment]
Verified point 18 against current DI2 server with SA-portal and CA-portal local clients.

SA-Portal will hoist the "Unknown" state to the top, whereas this is omitted in CA-Portal.
This behavior is true for both grouped and the flat list.
