### ISSUE TITLE
CA Customer report viewing across major browsers

### ISSUE THREAD

**Issue by scaspers** [scaspers/CA-Portal#5]
Since this is for our customers (public) we will need to support multiple browsers. 
Here is a report showing the top browsers (mobile & otherwise):
[Analytics www.protech-automotive.com Browser & OS 20171101-20180228.pdf](https://github.com/scaspers/CA-Portal/files/1974872/Analytics.www.protech-automotive.com.Browser.OS.20171101-20180228.pdf)

As of now it will display in chrome & firefox in windows7 and on Android.
When printing from chrome on win7 PC it will take a long time(large print file) this is a long known problem (2011) of chrome.  Their suggested work around is to save as PDF then open PDF in acrobat to print.  When printing from mobile chrome browser using google cloud print it prints normally (fast).
When printing from Firefox on win7 PC it will print fast but only the first page with a blank second page on a report that should have been 3 pages.
It will not display in IExplorer v11 on win7 PC.

Checked safari browser on iPhone5 and it displayed as expected.

**Comment by DanielCaspers** [comment]
[CA-Portal_ServiceWriter_Build05_DI2.zip](https://github.com/scaspers/CA-Portal/files/1976223/CA-Portal_ServiceWriter_Build05_DI2.zip)
[CA-Portal_ServiceWriter_Build05_DI.zip](https://github.com/scaspers/CA-Portal/files/1976224/CA-Portal_ServiceWriter_Build05_DI.zip)
[CA-Portal_Customer_Build-05-04-2018_DI2.zip](https://github.com/scaspers/CA-Portal/files/1976228/CA-Portal_Customer_Build-05-04-2018_DI2.zip)
[CA-Portal_Customer_Build-05-04-2018_DI.zip](https://github.com/scaspers/CA-Portal/files/1976229/CA-Portal_Customer_Build-05-04-2018_DI.zip)

Tested print media in FF and Chrome, but struggling to test in IE11 since they don't have print emulation dev tools. Looks good to me, but lmk what your thoughts are. Please lmk once you've uploaded to all servers so I can test Safari.

**Comment by DanielCaspers** [comment]
Tested again in the following browsers. Only minor issue was for SA-Portal on FF (#10) which was not the issue logged there, but the position of checkboxes.
