### ISSUE TITLE
Work Description & Order Notes are missing

### ISSUE THREAD

**Issue by scaspers** [scaspers/CA-Portal#6]
The order notes and work description heading are there but the data is not.  I think this happened with the last update.

**Comment by DanielCaspers** [comment]
Whoops........ I'll fix this tonight. Stupid me....

**Comment by DanielCaspers** [comment]
Here are the two builds.

[CA-Portal_ServiceWriter_Build06_DI2.zip](https://github.com/scaspers/CA-Portal/files/1982064/CA-Portal_ServiceWriter_Build06_DI2.zip)
[CA-Portal_ServiceWriter_Build06_DI.zip](https://github.com/scaspers/CA-Portal/files/1982065/CA-Portal_ServiceWriter_Build06_DI.zip)

As far as the "scroll workout" is concerned, please keep me updated. It should be **greatly** reduced, since I eliminated all  `<mat-expansion-panel>` padding on bottom of each item (by 16px each) and also reduced `<mat-expansion-panel-header>` height by 24px when expanded, and by 8px when collapsed. 
Go see on [Angular Material's site](https://material.angular.io/components/categories) if you wanna go learn about those components. 

In a 100 item inspection, with all items open, it should reduce by well over 2000px by my estimations, so that should hopefully remedy many of the issues.
