### ISSUE TITLE
Work Order notes/ work desc do not respect line feeds

### ISSUE THREAD

**Issue by scaspers** [scaspers/CA-Portal#8]
When a tech enters data and leaves space between comments to logically group them the service writers report joins all lines into one paragraph.  The desired response would be to retain the line feeds.

Tech's entry:
![image](https://user-images.githubusercontent.com/12421599/41004401-5b71ab8c-68df-11e8-9e20-f9e52252323a.png)

Service writers report:
![image](https://user-images.githubusercontent.com/12421599/41004410-6196ed92-68df-11e8-9f6b-c09ad4e434ba.png)

**Comment by DanielCaspers** [comment]
Lol, IIRC I explicitly asked you about this and you said you didn't care at that time. If you want to be brave and take a stab at it, you could add CSS whitespace pre to the order notes in CA or SA depending on branches you modify.

Else, I can do it quickly once schedule allows ;-)

**Comment by scaspers** [comment]
We should do the same for Work Desc also.

**Comment by DanielCaspers** [comment]
This is what I've changed for CA-portal specifically.

**Canned response descriptions** (the customer explanation) don't respect whitespace, because doing so currently causes inexplicably large whitespace gaps (think 3+ rows of text). Not sure why after a few minutes of investigation, so here's what I settled on for this field specifically.

![image](https://user-images.githubusercontent.com/6056563/42130474-d5066a70-7cab-11e8-8240-315519d0df2f.png)

**Inspection item notes**
![image](https://user-images.githubusercontent.com/6056563/42130497-ae9c9f5c-7cac-11e8-8c4c-4e8803b8cd8f.png)
